defaults:
  - train_cfg  # see train.py/TrainConfig
  - agent: iqrl  # see iqrl.py/iQRLConfig
  - override hydra/launcher: slurm  # Use slurm (on cluster) for multirun
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  verbose: false
  run:
    dir: output/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}
