name: iqrl
channels:
  - nvidia
  - pytorch
  - conda-forge
  - anaconda
  - menpo
dependencies:
  - python=3.9
  - pytorch=2.1.2 # This is overridden by post-install-amd.txt
  - torchvision
  - av # Needed for video logging with TorchRL
  # - pytorch-cuda=12.1
  # - pytorch-cuda=11.8
  - tensorboard
  - wandb=0.15
  - hydra-core=1.3
  - hydra-submitit-launcher=1.2
  - hydra-colorlog=1.2
  # - gymnasium=0.29
  - imageio  # For VideoRecorder in utils/video.py
  - imageio-ffmpeg # needed for rendering
  - ffmpeg # needed for rendering
  - moviepy  # For VideoRecorder in utils/video.py
  # For mujoco
  - glew
  - mesalib
  - mesa-libgl-cos6-x86_64
  - glfw3
  - seaborn
  - matplotlib
  - pip
  - pip:
      - numpy==1.26.4 # Needed to stop wandb raising numpy error
      - torchrl==0.3.1
      # - gymnasium[mujoco]==0.29.1
      # TODO metaworld wants to use gymnasium==1.0.0a1
      - git+https://github.com/Farama-Foundation/Metaworld.git@master#egg=metaworld==2.0.0
      - jaxtyping==0.2.23  # Types with shapes for tensors
      - dm_control==1.0.14  # Handles mujoco installation
      # - dm_control==1.0.15  # Handles mujoco installation
      - jaxtyping
      # - umap
      - vector_quantize_pytorch # This installs PyTorch (needs >2.0)
      # - gymnasium[mujoco]==0.29.1
      - tensordict==0.3.1
