defaults:
  - submitit_local
  # - override hydra/launcher: submitit_local

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
# submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 60
cpus_per_task: 1
# cpus_per_task: 6
gpus_per_node: 0
tasks_per_node: 1
# tasks_per_node: 6
mem_gb: 4
nodes: 1
name: ${hydra.job.name}
